services:
    mongo:
        image: mongo
        container_name: baitersburger-mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: baitersburger
    baitersburger-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: baitersburger-app
        ports:
            - 8080:8080
        depends_on:
            - mongo
